//
//  FAQsData.swift
//  MetaPi
//
//  Created by Veronika Nizhankivska on 2025-08-09.
//
import Foundation

enum FAQsData {
    static let all: [FAQSectionModel] = [
        FAQSectionModel(
            title: "Image Metadata",
            items: [
                FAQItem(
                    question: "What is EXIF metadata?",
                    answer: """
EXIF (Exchangeable Image File Format) is a standard for storing metadata in image files. It contains technical and primary information about a photo—such as date taken, date modified, GPS coordinates, camera model, lens info, exposure settings (ISO, shutter speed, aperture), and more. These details are automatically added by your camera or smartphone at the time of capture and can include hundreds of additional tags depending on the device and settings.
"""
                ),
                FAQItem(
                    question: "What is IPTC metadata?",
                    answer: """
IPTC (International Press Telecommunications Council) metadata is a standard used to store descriptive and administrative details about an image—such as title, caption, keywords, and more. It’s commonly used for organizing, publishing, and displaying photos, including on digital frames like Pi3D. IPTC metadata is also especially relevant for photographers and journalists, as it includes fields for copyright, author information, and usage rights.
"""
                ),
                FAQItem(
                    question: "What is Pi3D PictureFrame?",
                    answer: """
It is an open-source digital picture frame project for Raspberry Pi that displays photos with customizable transitions and embedded metadata like captions, dates, and locations. MetaPi was originally created to help users prepare images for Pi3D PictureFrame by editing metadata and formatting photos for display.
"""
                ),
                FAQItem(
                    question: "What metadata can I view in the app?",
                    answer: """
MetaPi lets you view a wide range of EXIF and IPTC metadata, including date/time, location, device info, camera settings, and descriptive fields. While not all possible metadata tags are shown, the app focuses on the most relevant ones for digital frames like Pi3D, along with other essential and widely-used metadata fields.
"""
                ),
                FAQItem(
                    question: "What metadata can I edit in the app?",
                    answer: """
You can edit all IPTC fields shown in the app, including title, caption, keywords, author, and more. For EXIF metadata, only a selected set of safe fields are editable—such as GPS location, date taken, user comments, device make and model, lens details, and selected technical fields (like focal length, exposure bias, etc.). This limitation helps prevent corruption of core EXIF data, which is automatically generated by the device when the photo is taken and is often unique to each image. Note: Many metadata fields require a specific format to be valid, so the app ensures proper formatting during editing.
"""
                ),
                FAQItem(
                    question: "What happens during batch metadata editing?",
                    answer: """
When editing multiple images at once, only the fields you change are updated across all selected images. Other metadata remains unchanged.
"""
                ),
                FAQItem(
                    question: "What does the “Missing Location” indicator mean?",
                    answer: """
This icon indicates that a photo has no GPS location metadata. In the app’s gallery, you’ll see a small label on photos that are missing location data. You can manually add or update the location in the metadata editor.
"""
                ),
                FAQItem(
                    question: "What happens when I delete metadata?",
                    answer: """
On iOS, MetaPi removes all metadata from your photo — including EXIF, TIFF, IPTC, GPS, XMP, ICC profiles, and any other embedded data. The image is saved as a JPEG at maximum quality (1.0) to preserve its visual appearance. Only the visual pixel data is kept; everything else is stripped.
"""
                ),
                FAQItem(
                    question: "What format should I use when editing metadata values?",
                    answer: """
In the metadata editing screen, each field includes a small info icon. Tap it to view a description of the tag and the supported input format. Following these format guidelines ensures your changes are applied correctly.
"""
                )
            ]
        ),
        FAQSectionModel(
            title: "Using the App",
            items: [
                FAQItem(
                    question: "What happens when I upload an image to the app?",
                    answer: """
When you upload an image to MetaPi, a copy is saved to the app’s internal storage with its original metadata preserved. The image is converted to JPEG format (if it’s not already) to ensure compatibility with editing and saving updated metadata. Nothing is uploaded or sent to any server—everything stays on your device until you choose to share it.
"""
                ),
                FAQItem(
                    question: "Can I save an image back to my phone’s gallery?",
                    answer: """
Yes. After editing, you can save a copy of the image—with all your metadata updates and edits—directly to your phone’s gallery.
"""
                ),
                FAQItem(
                    question: "What happens when I delete an image?",
                    answer: """
When you delete an image, it is permanently removed from MetaPi’s internal storage. This action does not delete the original photo from your phone’s gallery or other storage locations outside the app.
"""
                ),
                FAQItem(
                    question: "What happens when I save my edits (cropping or metadata)?",
                    answer: """
When you save your edits, MetaPi updates the original image stored in the app’s internal storage. Both visual changes (like cropping) and metadata edits are applied together. The EXIF "DateTimeDigitized" tag is also updated to reflect the time of saving.
"""
                ),
                FAQItem(
                    question: "Can I customize how metadata appears during editing?",
                    answer: """
Yes. You can filter metadata tags by type—EXIF or IPTC—and even apply a Pi3D-specific filter that highlights the most relevant fields for digital frame display. In the app’s settings, you can also choose a default filter, so every time you open the metadata editor, your preferred view is applied automatically.
"""
                ),
                FAQItem(
                    question: "What does “Storage Usage” mean in the app?",
                    answer: """
Storage usage shows how much space MetaPi’s imported images and cached data, such as thumbnails, are taking on your device. We include this info so you can monitor and manage the app’s storage usage. Note this only tracks the storage of files within the app — the total storage use including the app itself can be viewed in your device's system settings.
"""
                )
            ]
        ),
        FAQSectionModel(
            title: "Sharing & Compatibility",
            items: [
                FAQItem(
                    question: "Can I share multiple images at once?",
                    answer: """
Yes. From the Gallery screen, you can select multiple images, apply batch metadata edits, and then manually share them together using your device’s system sharing sheet.
"""
                ),
                FAQItem(
                    question: "Can I customize the sharing sheet?",
                    answer: """
The sharing sheet is managed by your device’s operating system, so customization is limited. Some devices allow limited adjustments in system settings, but MetaPi itself cannot control or modify how the sharing sheet looks or works.
"""
                ),
                FAQItem(
                    question: "Where can I share my images?",
                    answer: """
You can share to any compatible app on your device (e.g., Google Drive, Dropbox, Messages, Email) via the system sharing sheet.
"""
                ),
                FAQItem(
                    question: "What devices and iOS versions are compatible with MetaPi?",
                    answer: """
MetaPi is designed for iPhones running iOS 17.0 or later. For the best experience, we recommend using a modern, up-to-date device, as newer iOS versions provide improved performance, enhanced security, and better support for image editing and metadata management.
"""
                )
            ]
        )
    ]
}
